
### Authenticating a client of role ADMIN
POST http://localhost:8848/api/login
Content-Type: application/json

{
  "email": "britneyblankenship@quotezart.com",
  "password": "a0ece5db-cd14-4f21-812f-966633e7be86"
}

> {%
    client.global.set("auth_token", response.body.accessToken);
%}

### Authenticating a client of role USER
POST http://localhost:8848/api/login
Content-Type: application/json

{
  "email": "barnettblankenship@quotezart.com",
  "password": "a3b8d425-2b60-4ad7-becc-bedf2ef860bd"
}

> {%
    client.global.set("auth_token", response.body.accessToken);
%}

### Getting the client matching a name
# @no-redirect

GET http://localhost:8848/api/clients/search?field=name&value=Barnett
authorization: Bearer {{auth_token}}

### Getting a client
# @no-redirect

GET http://localhost:8848/api/clients/44e44268-dce8-4902-b662-1b34d2c10b8e
authorization: Bearer {{auth_token}}

### Getting the policy given a client name
# @no-redirect

GET http://localhost:8848/api/policies/search/client?field=name&value=Britney
authorization: Bearer {{auth_token}}

### Getting the client of a policy

GET http://localhost:8848/api/policies/7b624ed3-00d5-4c1b-9ab8-c265067ef58b/client
authorization: Bearer {{auth_token}}

###