
### AUTHENTICATING AN ADMIN
# @no-redirect
POST http://localhost:8848/api/login
Content-Type: application/json

{
  "email": "britneyblankenship@quotezart.com",
  "password": "a0ece5db-cd14-4f21-812f-966633e7be86"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### AUTHENTICATING AN USER
# @no-redirect
POST http://localhost:8848/api/login
Content-Type: application/json

{
  "email": "barnettblankenship@quotezart.com",
  "password": "a3b8d425-2b60-4ad7-becc-bedf2ef860bd"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### Get request with disabled redirects
# @no-redirect

GET http://localhost:8848/api/clients/search?field=name&value=Barnett
Cookie: AuthToken={{auth_token}}

### Get request with disabled redirects
# @no-redirect

GET http://localhost:8848/api/clients/44e44268-dce8-4902-b662-1b34d2c10b8e
Cookie: AuthToken={{auth_token}}

### Get request with disabled redirects
# @no-redirect

GET http://localhost:8848/api/policies/search/client?field=name&value=Britney
Cookie: AuthToken={{auth_token}}

### Get request with disabled redirects
# @no-redirect

GET http://localhost:8848/api/policies/7b624ed3-00d5-4c1b-9ab8-c265067ef58b/client
Cookie: AuthToken={{auth_token}}

###